"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from a .env file if available (optional)
try:
    from dotenv import load_dotenv
    _env_path = BASE_DIR = Path(__file__).resolve().parent.parent
    load_dotenv(os.path.join(_env_path, '.env'))
except Exception:
    # python-dotenv not installed or .env not present - continue using os.environ
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-k@%hjfc4s82lgj34@75k3be$icnrv!6r!tfnvaot*=5hl$8&vw')

# SECURITY WARNING: don't run with debug turned on in production!
_debug_env = os.getenv('DJANGO_DEBUG')
if _debug_env is None:
    DEBUG = True
else:
    DEBUG = str(_debug_env).lower() in ('1', 'true', 'yes')

# ALLOWED_HOSTS can be provided as a comma-separated list in DJANGO_ALLOWED_HOSTS
# Always ensure these sensible defaults are present for local testing and Render
_hosts = os.getenv('DJANGO_ALLOWED_HOSTS', '')
# Default hosts to include (always allow the Render hostname plus localhost)
# Ensure this is present even if BACKEND_RENDER_URL isn't provided in environment
_default_hosts = ['personal-portfolio-gsee.onrender.com', 'localhost', '127.0.0.1']

# Also allow specifying the backend URL directly (convenient for Render).
# `BACKEND_RENDER_URL` may include scheme; extract hostname for ALLOWED_HOSTS.
_backend_render_url = os.getenv('BACKEND_RENDER_URL', '')
if _backend_render_url:
    try:
        from urllib.parse import urlparse

        parsed = urlparse(_backend_render_url)
        backend_host = parsed.netloc or parsed.path  # netloc empty if no scheme
        # strip possible trailing slashes
        backend_host = backend_host.rstrip('/')
        if backend_host:
            _default_hosts.insert(0, backend_host)
    except Exception:
        # ignore parse errors and proceed with defaults
        pass
if _hosts:
    # Start with environment-provided hosts, then append defaults if missing
    ALLOWED_HOSTS = [h.strip() for h in _hosts.split(',') if h.strip()]
    for dh in _default_hosts:
        if dh not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(dh)
else:
    ALLOWED_HOSTS = _default_hosts.copy()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'contact.apps.ContactConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Place CORS middleware as early as possible so it can add headers
    # to responses generated by other middleware (including WhiteNoise).
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise after CorsMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use SQLite for both development and production
# For Render: the db.sqlite3 file persists in the writable /opt/render/project/src directory
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Use WhiteNoise's compressed manifest storage for static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# CORS: allow the Vite dev server during development
# In production, set CORS_ALLOWED_ORIGINS environment variable
_cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
_frontend_url = os.getenv('FRONTEND_URL', '')  # e.g. https://personal-portfolio-three-delta-53.vercel.app

# Start with development defaults
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Add FRONTEND_URL if provided (highest priority - Vercel/production frontend)
if _frontend_url:
    frontend = _frontend_url.strip().rstrip('/')
    if frontend:
        CORS_ALLOWED_ORIGINS.insert(0, frontend)

# Add additional origins from CORS_ALLOWED_ORIGINS if provided
if _cors_origins:
    additional_origins = [origin.strip().rstrip('/') for origin in _cors_origins.split(',') if origin.strip()]
    for origin in additional_origins:
        if origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(origin)

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Additional CORS settings for production
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGIN_REGEXES = []

# Email configuration
# Use console backend for development
# For production: use SMTP if credentials are provided, otherwise fall back to console/dummy
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # In production, check if email credentials are configured
    _email_user = os.getenv('EMAIL_HOST_USER', '')
    _email_pass = os.getenv('EMAIL_HOST_PASSWORD', '')
    if _email_user and _email_pass:
        # Use SMTP backend when credentials are available
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    else:
        # Fall back to console backend for logging (better than dummy for debugging)
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER', 'noreply@example.com')

# Security settings for production
if not DEBUG:
    # HTTPS/SSL
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Content Security
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Proxy settings (Render uses proxy)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
